# Generated by Django 5.0.6 on 2024-05-22 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CityList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ContractDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GraphList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margin', models.IntegerField()),
                ('win_probability', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_name', models.CharField(max_length=255, unique=True)),
                ('quantity', models.IntegerField()),
                ('price_a', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenders.accountlist')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenders.brand')),
                ('city_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenders.citylist')),
                ('contract_duration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenders.contractduration')),
                ('distributor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenders.distributor')),
                ('graph_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenders.graphlist')),
                ('month', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenders.month')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenders.state')),
            ],
        ),
        migrations.CreateModel(
            name='TenderB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_name', models.CharField(max_length=255, unique=True)),
                ('quantity', models.IntegerField()),
                ('price_b', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenders.accountlist')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenders.brand')),
                ('city_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenders.citylist')),
                ('contract_duration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenders.contractduration')),
                ('distributor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenders.distributor')),
                ('graph_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenders.graphlist')),
                ('month', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenders.month')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenders.state')),
            ],
        ),
    ]
